cpp.mk

This adds a common C++ build infrastructure makefile snippet which manages:
* Building release binaries
* Building test binaries
* Running tests
* Running coverage
* Running valgrind
* Managing build dependencies

Reviewer Rob - Common C++ build infrastructure

---

cpp.mk

- Allow makefiles to specify ROOT, and default other values from that
- Silence the output of "make clean"

Makefile tweaks

---

cpp.mk

More thorough and also more maintainable to wipe out entire directories
rather than trying to pick out all targets individually

Improve 'make clean'

---

cpp.mk

It's sufficient for the makefile to include these; there's no need
also to depend on them.
In particular, clang produces .d files that are newer than .o files -
which leads to unnecessary rebuilding next time round.

Don't depend on dependency files

---

cpp.mk

After running `make coverage_raw` my directory is filled with `.gcov` files.  Probably not useful.

Don't keep raw gcov files

---

cpp.mk

This prevented the last .d file being included, which could cause things to not be rebuilt.

[Already reviewed by Andy] Remove rogue curly brace

---

cw-deb.mk

This avoids the slightly annoying:
```
dpkg-scanpackages: warning: Packages in archive but missing from override file:
dpkg-scanpackages: warning:   astaire astaire-dbg astaire-libs ...
```
warning. I've successfully built a set of packages with this.
(Credit to @AME2 who asked why we got that warning, which prompted me to look into it.)

[Reviewer: Andy] Don't specify /dev/null as the override file

---

cpp.mk

Allow the root option passed to the gcovr script to be configurable by makefiles (needed for cpp-common-test)

[Reviewer: Adam] Allow the coverage root to be configured by makefiles

---

cpp.mk

Don't always wildcard the JUSTTEST arg

[Reviewer: Adam] Don't always have stars

---

cpp.mk

Clean out the coverage files between runs so that we detect when coverage falls

[Reviewer: Adam] Allow coverage to fall

---

cpp.mk

Like https://github.com/Metaswitch/clearwater-build-infra/commit/3ccfa7a14c27cc3fed52b39585fdd9b7c75e6d95 but runs whenever running tests. This deals with some Clang errors I'm seeing:
`profiling: /home/ubuntu/stats-aggregator/src/../build/stats_aggregator_test/aggregators_test.gcda: cannot merge previous GCDA file: corrupt arc tag (0x73317463)`
which is because the file has changed but I'm trying to update an old coverage file with new data.

[Reviewer: Ellie] Remove old coverage files when re-running tests

---

cpp.mk

Rob was complaining that `make full_test` doesn't work projects with no TEST_TARGETS defined, this just defaults those projects to have empty lists for `TARGETS`/`TEST_TARGETS`.

Reviewer Alex - Allow ommitting TARGETS or TEST_TARGETS

---

deb2rpm.pl

Changes deb2rpm to add a space between the package name, '=', and the version number, so that dependencies work correctly.

[Reviewer: Matt] Fix spacing in package dependencies

---

cw-deb.mk
cw-rpm.mk

HI Matt, 
This PR enhances `cw-rpm.mk` to decouple "which spec files to build" from "which packages to expect have been built". This is needed because of the way debug packages work on centos - the debug package is build from the same spec file as the main package, so you end up with one spec file producing two (differently named) rpms.
I've tested that this works by building a project with a debug package and checking that the debug package is built, and is moved along with the main package if `REPO_DIR` is set. 
Thanks,
Alex.

[Reviewer: Matt] Allow spec files to be specified separately from output packages

---

cw-rpm.spec.inc

This PR makes debuginfo packages have an explicit versioned dependecy on the parent
package, and also on gdb. 
Most if this is a straight copy of the macro in `debug_package` in `/usr/lib/rpm/macros`. I've changed the name to `cw_debug_package` and added the extra Requires line. 
I'll update the relevant spec files to use the new macro, but won't bother you with those trivial PRs. 
I've checked that installing the debuginfo package also installs gdb. If you upgrade either the main package or the debginfo, both get upgraded.

[Reviewer: Matt] Enhance debuginfo packages

---

cw-rpm.spec.inc

This PR enhances the RPM specfile includes to allow the RPM's license and URL to be overriden.

[Reviewer: Matt] Allow the license and project URL to be overridden

---

cpp.mk

This can be useful, for example, if particular files want no optimisation, or higher-level optimisations (-O3).

[Reviewer: Alex] Allow per-file CPPFLAGS

---

cw-module-install.mk

'Install' submodules to a separate directory and then rsync the changed ones
into place only caring about differing checksums.
As per https://github.com/Metaswitch/sprout/pull/1474

[Reviewer: MIRW] Incremental build with installed submodules

---

cw-deb.mk

This PR allows multiple repo servers to be defined when copying debs.

[Reviewer: Matt] Allow multiple REPO SERVERS

---

cw-rpm-utils
deb2rpm.pl

This is a follow on to https://github.com/Metaswitch/clearwater-etcd/pull/355, https://github.com/Metaswitch/clearwater-infrastructure/pull/394, https://github.com/Metaswitch/sprout/pull/1588, https://github.com/Metaswitch/ellis/pull/194 and https://github.com/Metaswitch/clearwater-readthedocs/pull/223 to provide function to convert the debian links files in those PRs to spec file instuctions to create the same links in RPMs.
Tested by running these changes in clearwater-infrastructure to create the new spec file, generated an RPM from this and installed it on a CentOS box.  Links were created as expected and removed again when the RPM was erased.

[Reviewer EM] Add migration of debian links to rpms

---

cw-rpm-move.mk
cw-rpm.mk

This separates out rpm-move targets into a separate Makefile, so they can be included separately from the rpm-build target.
It also allows the caller to pass a custom directory containing the RPMs (RPM_ARCH_DIR and RPM_NOARCH_DIR).

[Reviewer: Ellie] Separate out rpm-move targets 

---

cw-deb.mk
cw-pkg.mk

I am not sure where is the LICENSE file path used in cw-deb.mk defined. It's supposed to change from some_repository/clearwater-build-infra/LICENSE to just some_repository/LICENSE.

Different license in make file

---

deb2rpm.pl

As summary - this update allows a package to specify an `<package>.rsyslog` file, which gets copied to `/etc/rsyslog.d/<package>.conf` during RPM installation.

Ensure that package-specific rsyslog.d files are copied into place during RPM installation.

---

cw-rpm.mk
cw-rpm.spec.inc

Updates cw-rpm.mk to correctly set the `LICENSE` and `URL` fields.
I had to have a few goes to get the syntax right to pass the variables around, but I've tested this and it works with the `clearwater-monit` library.
(Apologies about the previous one - looks like I accidentally included some additional commits because the branch I pushed was built on top of `clearwater-core`)

Fixing `make rpm` to add the correct licensing information

---

python.mk

This is being done as part of the Python packaging work.
In order to avoid defining some common Python based definitions in every Makefile, I've put them in python.mk.
See https://github.com/Metaswitch/crest/pull/362 for the context this is being done in.

[Reviewer: Seb] Add useful stuff to python.mk

---

python.mk

Seb,
Currently most things install bandit using easy_install, whereas somethings use pip. This consolidates them to both use pip.
Generally, we should move away from using `easy_install` and move to using `pip` everywhere.

[Reviewer: Seb] Install bandit using pip

---

cpp.mk

This adds the option to exclude tests from the valgrind check.
This lays the groundwork for https://github.com/Metaswitch/sprout/pull/1948 which allows us to speed up sprout's `make full_test` in most cases
Any target can define a `<target>_VALGRIND_EXCL`, which must be a google test filter that matches on the tests that should be excluded.

[Reviewer: Adam] Allow tests to be excluded from Valgrind

---

cpp.mk

This ensures we get formatted coverage output in build logs

[Reviewer: Richard] Include coverage_raw on full_test

---

python.mk

Adds more common infrastructure to our python.mk, which allows us to re-use it across repositories.
The commonalized parts are:
* wheel building and installation in now done using the `python_component` macro
* coverage
* verify
* style
* clean
(`explain-style` has been removed as it doesn't work with new versions of `flake8`)
Hopefully the comments are sufficient to explain what this all does. If not, I'll update the comments rather than adding more detail to the PR

[Reviewer: Richard] Common python build infra

---

python.mk

Two small enhancements to the Python code.
- Allow a different version of setuptools to be used. Now that we are using pip, we don't need to be stuck on 24, and importantly `nsenter` requires > 30.
- Build directories should be relative to the root directory.
These changes are needed to build the changes in https://github.com/Metaswitch/clearwater-infrastructure/pull/288

[Reviewer: Seb] Python enhancements

---

python.mk

I tested in python-common, using this version of build-infra, by running the following commands:
- make env
- make clean
- make envclean
- make pyclean
That all worked fine.
Then I ran `find . -name "*dist*"` from the root of python-common, and nothing showed up.

Remove old line

---

python.mk

This is an attempt to rationalise the dependencies of our common python makefile infrastructure.
Key changes:
1. Instead of setting python and pip as dependencies, we now have a sentinel file in the venv (`ENV_DIR/.env`) which indicates that we've installed python, pip and wheel. This is to mitigate the fact that sometimes pip would appear as more recent that some of the other sentinel files, which would cause us to delete the entire venv and hence do a full rebuild
1. Components can now either be added as a full component (which builds a wheel) or a test component (which just provides some test targets). Full components include the test components, but add additional targets on top
1. The dependency structure for tests is:
* each component or test component adds a `<name>_test` target …

[Reviewer: Richard] Python makefile improvements

---

cpp.mk
python.mk

This PR adds the cpp analysis command as part of build-infra, and adds analysis_version commands that show the version of the analysis tools used. The cpp analysis target can only be used by the standard builds - however only the standard builds use cpp,mk, so I don't see that as a limitation.
Tested by running the commands over the various repos.
I'll also:
* Change any job in Jenkins that uses cpp.mk to call make analysis rather than the Jenkins script
* Add clang as a test dependency to the cpp repos.

[Reviewer: Krista] Add bandit and clang checks to makefiles

---

python.mk

As discussed `virtualenv` doesn't support python3, the new model is `python3 -m venv`.
The detection here is a little hokey, but the precedent for the input values forces my hand somewhat.

[Reviewer RJW2] Don't use virtualenv for python3
